name: publish
on:
  release:
    types:
      - published
permissions:
  id-token: write
  contents: read
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: jetify-com/devbox-install-action@v0.15.0

      - run: devbox run -- pnpm install --frozen-lockfile
      - run: devbox run -- pnpm run build
      - run: devbox run -- pnpm publish --access=public
